In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot('amazing restaurant', 30)

[2, 3]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[28, 16], [2, 3], [1, 16], [14, 9, 9], [2, 2, 1], [4, 16], [16, 2, 10], [15, 16], [15, 4], [26, 1]]


In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, max_length, padding='post')
print(padded_reviews)

[[28 16  0]
 [ 2  3  0]
 [ 1 16  0]
 [14  9  9]
 [ 2  2  1]
 [ 4 16  0]
 [16  2 10]
 [15 16  0]
 [15  4  0]
 [26  1  0]]


In [12]:
X = padded_reviews
y = sentiment

In [13]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X, y, epochs=50, verbose=0)

In [16]:
loss,accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 131ms/step - loss: 0.6354 - accuracy: 1.0000


1.0

In [18]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [ ]:
# let see nice (28) and good (16)

In [21]:
print(weights[28])
print(weights[16])

[ 0.07924981  0.07094556  0.0154256  -0.06411143]
[-0.04198041 -0.01253189 -0.03535658  0.07393441]
