In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [5]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [6]:
text_test = ['nice movie indeed','I love python programming']
text_preprocess = bert_preprocess_model(text_test)
text_preprocess.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [10]:
#text_preprocess['input_mask']
# CLS nice movie indeed SEP (That's why we have 5 token)

In [11]:
#text_preprocess['input_type_ids']

In [12]:
#text_preprocess['input_word_ids']

In [13]:
bert_model = hub.KerasLayer(encoder_url)
bert_result = bert_model(text_preprocess)
bert_result.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [14]:
bert_result['pooled_output'] # Embedding vector for two above sentence

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7916381 , -0.21401832,  0.49778825, ...,  0.2445495 ,
        -0.47325817,  0.8175386 ],
       [-0.91703737, -0.47904378, -0.78609234, ..., -0.61709267,
        -0.71006066,  0.9218161 ]], dtype=float32)>

In [15]:
bert_result['sequence_output'] # Indivitual word Embedding vector

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07296449,  0.08557408,  0.14468797, ..., -0.09657122,
          0.08712933,  0.07727157],
        [ 0.17859878, -0.19009805,  0.5033989 , ..., -0.05882023,
          0.32694456, -0.15579712],
        [ 0.18710195, -0.4340848 , -0.48876804, ..., -0.15496314,
          0.00146329, -0.24453509],
        ...,
        [ 0.12061725,  0.12885782,  0.4645589 , ...,  0.07372758,
          0.17414734,  0.1653504 ],
        [ 0.07949206, -0.01211711,  0.5025364 , ...,  0.13790885,
          0.20990229,  0.0061568 ],
        [-0.0722513 , -0.2831484 ,  0.59030867, ...,  0.47551867,
          0.16647315, -0.08913229]],

       [[-0.07882559,  0.36319512, -0.21078998, ..., -0.17139482,
          0.16300714,  0.67262447],
        [ 0.2789909 ,  0.43677995, -0.35746235, ..., -0.04435221,
          0.38312963,  0.5891633 ],
        [ 1.2044512 ,  1.0724102 ,  0.48439223, ...,  0.24897118,
          0.40699008,  0.40525174],
        ...,

In [17]:
len(bert_result['encoder_outputs']) # We are using BERT Base

12

In [21]:
bert_result['encoder_outputs'][-1]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07296449,  0.08557408,  0.14468797, ..., -0.09657122,
          0.08712933,  0.07727157],
        [ 0.17859878, -0.19009805,  0.5033989 , ..., -0.05882023,
          0.32694456, -0.15579712],
        [ 0.18710195, -0.4340848 , -0.48876804, ..., -0.15496314,
          0.00146329, -0.24453509],
        ...,
        [ 0.12061725,  0.12885782,  0.4645589 , ...,  0.07372758,
          0.17414734,  0.1653504 ],
        [ 0.07949206, -0.01211711,  0.5025364 , ...,  0.13790885,
          0.20990229,  0.0061568 ],
        [-0.0722513 , -0.2831484 ,  0.59030867, ...,  0.47551867,
          0.16647315, -0.08913229]],

       [[-0.07882559,  0.36319512, -0.21078998, ..., -0.17139482,
          0.16300714,  0.67262447],
        [ 0.2789909 ,  0.43677995, -0.35746235, ..., -0.04435221,
          0.38312963,  0.5891633 ],
        [ 1.2044512 ,  1.0724102 ,  0.48439223, ...,  0.24897118,
          0.40699008,  0.40525174],
        ...,